ProjetTexcel-WEB/ProjetTexcel-WEB/Controllers/tblGenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetTexcel_WEB;

namespace ProjetTexcel_WEB.Controllers
{
    public class tblGenresController : Controller
    {
        private bdTexelFredAlexEntities db = new bdTexelFredAlexEntities();

        // GET: tblGenres
        public ActionResult Index(string search)
        {
            var genre = from s in db.tblGenre
                        select s;
            if(!String.IsNullOrEmpty(search))
            {
                genre = genre.Where(s => s.tag.Contains(search));
            }
            return View(genre.ToList());
        }

        // GET: tblGenres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGenre tblGenre = db.tblGenre.Find(id);
            if (tblGenre == null)
            {
                return HttpNotFound();
            }
            return View(tblGenre);
        }

        // GET: tblGenres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblGenres/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idGenre,nom,description,tag")] tblGenre tblGenre)
        {
            if (ModelState.IsValid)
            {
                db.tblGenre.Add(tblGenre);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblGenre);
        }

        // GET: tblGenres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGenre tblGenre = db.tblGenre.Find(id);
            if (tblGenre == null)
            {
                return HttpNotFound();
            }
            return View(tblGenre);
        }

        // POST: tblGenres/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idGenre,nom,description,tag")] tblGenre tblGenre)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblGenre).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblGenre);
        }

        // GET: tblGenres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblGenre tblGenre = db.tblGenre.Find(id);
            if (tblGenre == null)
            {
                return HttpNotFound();
            }
            return View(tblGenre);
        }

        // POST: tblGenres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblGenre tblGenre = db.tblGenre.Find(id);
            db.tblGenre.Remove(tblGenre);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblGenres/Create.cshtml
@model ProjetTexcel_WEB.tblGenre

@{
    ViewBag.Title = "Ajouter";
}

<h2>Ajouter</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Description</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblGenres/Delete.cshtml
@model ProjetTexcel_WEB.tblGenre

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sur de vouloir supprimer ce genre ?</h3>
<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>


    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblGenres/Details.cshtml
@model ProjetTexcel_WEB.tblGenre

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Genre</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
           Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>


    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idGenre }) |
    @Html.ActionLink("Retour", "Index")
</p>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblGenres/Edit.cshtml
@model ProjetTexcel_WEB.tblGenre

@{
    ViewBag.Title = "Éditer";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Genre</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idGenre)

        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Description</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblGenres/Index.cshtml
@model IEnumerable<ProjetTexcel_WEB.tblGenre>

@{
    ViewBag.Title = "Genres";
}
<<h2>@ViewBag.Title</h2>


 <p>
    @Html.ActionLink("Ajouter", "Create")
</p>

<div class="formContainer">
    
   
 @using (Html.BeginForm("Index", "tblGenres", FormMethod.Post))
 {
     @Html.TextBox("search")
    <input type="submit" value="Search" />
 }
<table class="table">
    <tr>
        <th>
            Nom
        </th>
        <th>
           Description
        </th>
        
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        
        <td>
            @Html.ActionLink("Éditer", "Edit", new { id=item.idGenre }) |
            @Html.ActionLink("Détails", "Details", new { id=item.idGenre }) |
            @Html.ActionLink("Supprimer", "Delete", new { id=item.idGenre })
        </td>
    </tr>
}

</table>
    </div>