ProjetTexcel-WEB/ProjetTexcel-WEB/Controllers/tblClassificationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetTexcel_WEB;

namespace ProjetTexcel_WEB.Controllers
{
    public class tblClassificationsController : Controller
    {
        private bdTexelFredAlexEntities db = new bdTexelFredAlexEntities();

        // GET: tblClassifications
        
        public ActionResult Index(string search)
        {
            var classif = from s in db.tblClassification
                          select s;
            if(!String.IsNullOrEmpty(search))
            {
                classif = classif.Where(s => s.tag.Contains(search));

            }
            return View(classif.ToList());
        }

        // GET: tblClassifications/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblClassification tblClassification = db.tblClassification.Find(id);
            if (tblClassification == null)
            {
                return HttpNotFound();
            }
            return View(tblClassification);
        }

        // GET: tblClassifications/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: tblClassifications/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idClassification,nom,description,tag")] tblClassification tblClassification)
        {
            if (ModelState.IsValid)
            {
                db.tblClassification.Add(tblClassification);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tblClassification);
        }

        // GET: tblClassifications/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblClassification tblClassification = db.tblClassification.Find(id);
            if (tblClassification == null)
            {
                return HttpNotFound();
            }
            return View(tblClassification);
        }

        // POST: tblClassifications/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idClassification,nom,description,tag")] tblClassification tblClassification)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblClassification).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tblClassification);
        }

        // GET: tblClassifications/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblClassification tblClassification = db.tblClassification.Find(id);
            if (tblClassification == null)
            {
                return HttpNotFound();
            }
            return View(tblClassification);
        }

        // POST: tblClassifications/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblClassification tblClassification = db.tblClassification.Find(id);
            db.tblClassification.Remove(tblClassification);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblClassifications/Create.cshtml
@model ProjetTexcel_WEB.tblClassification

@{
    ViewBag.Title = "Ajouté";
}

<h2>Ajouté</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Classification</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div>
            <p class="control-label col-md-2">Nom</p> 
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div>
                <p class="control-label col-md-2">Description</p>

                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouté" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblClassifications/Delete.cshtml
@model ProjetTexcel_WEB.tblClassification

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sur de vouloir supprimer cette Classification ?</h3>
<div>
    <h4>Classification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblClassifications/Details.cshtml
@model ProjetTexcel_WEB.tblClassification

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Classification</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
           Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idClassification }) |
    @Html.ActionLink("Retour", "Index")
</p>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblClassifications/Edit.cshtml
@model ProjetTexcel_WEB.tblClassification

@{
    ViewBag.Title = "Éditer";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Classification</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idClassification)

        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Description</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblClassifications/Index.cshtml
@model IEnumerable<ProjetTexcel_WEB.tblClassification>

@{
    ViewBag.Title = "Classifications";
}


<h2>@ViewBag.Title</h2>


 <p>
    @Html.ActionLink("Ajouter", "Create")
</p>

<div class="formContainer">
    
   
 @using (Html.BeginForm("Index", "tblClassifications", FormMethod.Post))
 {
     @Html.TextBox("search")
    <input type="submit" value="Search" />
 }

    <table class="table">
        <tr>
            <th>
                Nom
            </th>
            <th>
                Description
            </th>
            <th></th>
            </tr>


@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.nom)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        
        <td>
            @Html.ActionLink("Éditer", "Edit", new { id = item.idClassification }) |
            @Html.ActionLink("Détails", "Details", new { id = item.idClassification }) |
            @Html.ActionLink("Supprimer", "Delete", new { id = item.idClassification })
        </td>
    </tr>
}


        
    </table>
</div>