ProjetTexcel-WEB/ProjetTexcel-WEB/Controllers/tblPlatformsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetTexcel_WEB;

namespace ProjetTexcel_WEB.Controllers
{
    public class tblPlatformsController : Controller
    {
        private bdTexelFredAlexEntities db = new bdTexelFredAlexEntities();

        // GET: tblPlatforms
        public ActionResult Index(string search)
        {
            var tblPlatform = from s in db.tblPlatform.Include(t => t.tblSystemExploitation)
                              select s;
            if(!String.IsNullOrEmpty(search))
            {
                tblPlatform = tblPlatform.Where(s => s.tag.Contains(search));
            }
            return View(tblPlatform.ToList());
        }

        // GET: tblPlatforms/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPlatform tblPlatform = db.tblPlatform.Find(id);
            if (tblPlatform == null)
            {
                return HttpNotFound();
            }
            return View(tblPlatform);
        }

        // GET: tblPlatforms/Create
        public ActionResult Create()
        {
            ViewBag.idSysExp = new SelectList(db.tblSystemExploitation, "idSysExp", "nom");
            return View();
        }

        // POST: tblPlatforms/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idPlatform,nom,config,typePlatform,idSysExp,tag")] tblPlatform tblPlatform)
        {
            if (ModelState.IsValid)
            {
                db.tblPlatform.Add(tblPlatform);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idSysExp = new SelectList(db.tblSystemExploitation, "idSysExp", "nom", tblPlatform.idSysExp);
            return View(tblPlatform);
        }

        // GET: tblPlatforms/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPlatform tblPlatform = db.tblPlatform.Find(id);
            if (tblPlatform == null)
            {
                return HttpNotFound();
            }
            ViewBag.idSysExp = new SelectList(db.tblSystemExploitation, "idSysExp", "nom", tblPlatform.idSysExp);
            return View(tblPlatform);
        }

        // POST: tblPlatforms/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idPlatform,nom,config,typePlatform,idSysExp,tag")] tblPlatform tblPlatform)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblPlatform).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idSysExp = new SelectList(db.tblSystemExploitation, "idSysExp", "nom", tblPlatform.idSysExp);
            return View(tblPlatform);
        }

        // GET: tblPlatforms/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblPlatform tblPlatform = db.tblPlatform.Find(id);
            if (tblPlatform == null)
            {
                return HttpNotFound();
            }
            return View(tblPlatform);
        }

        // POST: tblPlatforms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblPlatform tblPlatform = db.tblPlatform.Find(id);
            db.tblPlatform.Remove(tblPlatform);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblPlatforms/Create.cshtml
@model ProjetTexcel_WEB.tblPlatform

@{
    ViewBag.Title = "Ajouter";
}

<h2>Ajouter</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Platforme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Configuration minimal</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.config, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.config, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Type de Platforme</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.typePlatform, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.typePlatform, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Système d'exploitation</p>
            <div class="col-md-10">
                @Html.DropDownList("idSysExp", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSysExp, "", new { @class = "text-danger" })
            </div>
        </div>
         <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblPlatforms/Delete.cshtml
@model ProjetTexcel_WEB.tblPlatform

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sur de vouloir supprimer cette platforme ?</h3>
<div>
    <h4>Platform</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            Configuration minimal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.config)
        </dd>

        <dt>
            Type de Platformes
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typePlatform)
        </dd>

         <dt>
            Système d'exploitation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSystemExploitation.nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblPlatforms/Details.cshtml
@model ProjetTexcel_WEB.tblPlatform

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Platform</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            Configuration minimal
        </dt>

        <dd>
            @Html.DisplayFor(model => model.config)
        </dd>

        <dt>
            Type de Platformes
        </dt>

        <dd>
            @Html.DisplayFor(model => model.typePlatform)
        </dd>

        <dt>
            Système d'exploitation
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblSystemExploitation.nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idPlatform }) |
    @Html.ActionLink("Retour", "Index")
</p>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblPlatforms/Edit.cshtml
@model ProjetTexcel_WEB.tblPlatform

@{
    ViewBag.Title = "Éditer";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Platforme</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idPlatform)

        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Configuration</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.config, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.config, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Type de Platforme</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.typePlatform, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.typePlatform, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Système d'exploitation</p>
            <div class="col-md-10">
                @Html.DropDownList("idSysExp", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSysExp, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblPlatforms/Index.cshtml
@model IEnumerable<ProjetTexcel_WEB.tblPlatform>

@{
    ViewBag.Title = "Platformes";
}
<h2>@ViewBag.Title</h2>


<p>
    @Html.ActionLink("Ajouter", "Create")
</p>

<div class="formContainer">


    @using (Html.BeginForm("Index", "tblPlatforms", FormMethod.Post))
    {
        @Html.TextBox("search")
        <input type="submit" value="Search" />
    }
    <table class="table">
        <tr>
            <th>
                Nom
            </th>
            <th>
                Configuration Matériel
            </th>
            <th>
                Type de Platforme
            </th>
            <th>
                Système d'exploitation
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.config)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.typePlatform)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblSystemExploitation.nom)
                </td>
                <td>
                    @Html.ActionLink("Éditer", "Edit", new { id = item.idPlatform }) |
                    @Html.ActionLink("Détails", "Details", new { id = item.idPlatform }) |
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.idPlatform })
                </td>
            </tr>
        }

    </table>
</div>