ProjetTexcel-WEB/ProjetTexcel-WEB/Controllers/tblJeusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProjetTexcel_WEB;

namespace ProjetTexcel_WEB.Controllers
{
    public class tblJeusController : Controller
    {
        private bdTexelFredAlexEntities db = new bdTexelFredAlexEntities();

        // GET: tblJeus
        public ActionResult Index(string search)
        {
            var tblJeu = from s in db.tblJeu.Include(t => t.tblClassification).Include(t => t.tblGenre).Include(t => t.tblPlatform).Include(t => t.tblTheme)
                         select s;
            if(!String.IsNullOrEmpty(search))
            {
                tblJeu = tblJeu.Where(s => s.tag.Contains(search));
            }
            return View(tblJeu.ToList());
        }

        // GET: tblJeus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblJeu tblJeu = db.tblJeu.Find(id);
            if (tblJeu == null)
            {
                return HttpNotFound();
            }
            return View(tblJeu);
        }

        // GET: tblJeus/Create
        public ActionResult Create()
        {
            ViewBag.idClassification = new SelectList(db.tblClassification, "idClassification", "nom");
            ViewBag.idGenre = new SelectList(db.tblGenre, "idGenre", "nom");
            ViewBag.idPlatform = new SelectList(db.tblPlatform, "idPlatform", "nom");
            ViewBag.idTheme = new SelectList(db.tblTheme, "idTheme", "nom");
            return View();
        }

        // POST: tblJeus/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idJeu,developpeur,description,minimalConfig,idClassification,idGenre,idTheme,idPlatform,nom,tag")] tblJeu tblJeu)
        {
            if (ModelState.IsValid)
            {
                db.tblJeu.Add(tblJeu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idClassification = new SelectList(db.tblClassification, "idClassification", "nom", tblJeu.idClassification);
            ViewBag.idGenre = new SelectList(db.tblGenre, "idGenre", "nom", tblJeu.idGenre);
            ViewBag.idPlatform = new SelectList(db.tblPlatform, "idPlatform", "nom", tblJeu.idPlatform);
            ViewBag.idTheme = new SelectList(db.tblTheme, "idTheme", "nom", tblJeu.idTheme);
            return View(tblJeu);
        }

        // GET: tblJeus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblJeu tblJeu = db.tblJeu.Find(id);
            if (tblJeu == null)
            {
                return HttpNotFound();
            }
            ViewBag.idClassification = new SelectList(db.tblClassification, "idClassification", "nom", tblJeu.idClassification);
            ViewBag.idGenre = new SelectList(db.tblGenre, "idGenre", "nom", tblJeu.idGenre);
            ViewBag.idPlatform = new SelectList(db.tblPlatform, "idPlatform", "nom", tblJeu.idPlatform);
            ViewBag.idTheme = new SelectList(db.tblTheme, "idTheme", "nom", tblJeu.idTheme);
            return View(tblJeu);
        }

        // POST: tblJeus/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idJeu,developpeur,description,minimalConfig,idClassification,idGenre,idTheme,idPlatform,nom,tag")] tblJeu tblJeu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tblJeu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idClassification = new SelectList(db.tblClassification, "idClassification", "nom", tblJeu.idClassification);
            ViewBag.idGenre = new SelectList(db.tblGenre, "idGenre", "nom", tblJeu.idGenre);
            ViewBag.idPlatform = new SelectList(db.tblPlatform, "idPlatform", "nom", tblJeu.idPlatform);
            ViewBag.idTheme = new SelectList(db.tblTheme, "idTheme", "nom", tblJeu.idTheme);
            return View(tblJeu);
        }

        // GET: tblJeus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tblJeu tblJeu = db.tblJeu.Find(id);
            if (tblJeu == null)
            {
                return HttpNotFound();
            }
            return View(tblJeu);
        }

        // POST: tblJeus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tblJeu tblJeu = db.tblJeu.Find(id);
            db.tblJeu.Remove(tblJeu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblJeus/Create.cshtml
@model ProjetTexcel_WEB.tblJeu

@{
    ViewBag.Title = "Ajouter";
}

<h2>Ajouter</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jeu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <p class="control-label col-md-2">Développeur</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.developpeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.developpeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Description</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Configuration matérielle minimal</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.minimalConfig, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minimalConfig, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Classification</p>
            <div class="col-md-10">
                @Html.DropDownList("idClassification", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idClassification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Genre</p>
            <div class="col-md-10">
                @Html.DropDownList("idGenre", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Thème</p>
            <div class="col-md-10">
                @Html.DropDownList("idTheme", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTheme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Platforme</p>
            <div class="col-md-10">
                @Html.DropDownList("idPlatform", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idPlatform, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblJeus/Delete.cshtml
@model ProjetTexcel_WEB.tblJeu

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer</h2>

<h3>Êtes-vous sur de vouloir Suprrimer ce Jeu ?</h3>
<div>
    <h4>Jeu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Développeur
        </dt>

        <dd>
            @Html.DisplayFor(model => model.developpeur)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            Configuration Matérielle Minimum
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimalConfig)
        </dd>

        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        <dt>
            Classification
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblClassification.nom)
        </dd>

        <dt>
            Genre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblGenre.nom)
        </dd>

        <dt>
            Platoforme
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPlatform.nom)
        </dd>

        <dt>
            Thème
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTheme.nom)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retour", "Index")
        </div>
    }
</div>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblJeus/Details.cshtml
@model ProjetTexcel_WEB.tblJeu

@{
    ViewBag.Title = "Détails";
}

<h2>Détails</h2>

<div>
    <h4>Jeu</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Développeur
        </dt>

        <dd>
            @Html.DisplayFor(model => model.developpeur)
        </dd>

        <dt>
            Description
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            Matérielle minimum
        </dt>

        <dd>
            @Html.DisplayFor(model => model.minimalConfig)
        </dd>

        <dt>
            Nom
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nom)
        </dd>

        

        <dt>
            Classification
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblClassification.nom)
        </dd>

        <dt>
            Genre
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblGenre.nom)
        </dd>

        <dt>
            Platforme
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblPlatform.nom)
        </dd>

        <dt>
            Thème
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tblTheme.nom)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Éditer", "Edit", new { id = Model.idJeu }) |
    @Html.ActionLink("Retour", "Index")
</p>

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblJeus/Edit.cshtml
@model ProjetTexcel_WEB.tblJeu

@{
    ViewBag.Title = "Éditer";
}

<h2>Éditer</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Jeu</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.idJeu)

        <div class="form-group">
            <p class="control-label col-md-2">Développeur</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.developpeur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.developpeur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Description</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Configuration Matérielle minimum</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.minimalConfig, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.minimalConfig, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Classification</p>
            <div class="col-md-10">
                @Html.DropDownList("idClassification", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idClassification, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Genre</p>
            <div class="col-md-10">
                @Html.DropDownList("idGenre", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idGenre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Thème</p>
            <div class="col-md-10">
                @Html.DropDownList("idTheme", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idTheme, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Platforme</p>
            <div class="col-md-10">
                @Html.DropDownList("idPlatform", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idPlatform, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <p class="control-label col-md-2">Nom</p>
            <div class="col-md-10">
                @Html.EditorFor(model => model.nom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nom, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sauvegarder" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProjetTexcel-WEB/ProjetTexcel-WEB/Views/tblJeus/Index.cshtml
@model IEnumerable<ProjetTexcel_WEB.tblJeu>

@{
    ViewBag.Title = "Jeux";
}
<h2>@ViewBag.Title</h2>


<p>
    @Html.ActionLink("Ajouter", "Create")
</p>

<div class="formContainer">


    @using (Html.BeginForm("Index", "tblJeus", FormMethod.Post))
    {
        @Html.TextBox("search")
        <input type="submit" value="Search" />
    }
    <table class="table">
        <tr>
            <th>
                Développeur
            </th>
            <th>
                Description
            </th>
            <th>
                Configuration Matérielle Minimum
            </th>
            <th>
                Nom
            </th>

            <th>
                Classification
            </th>
            <th>
                Genre
            </th>
            <th>
                Platforme
            </th>
            <th>
                Thème
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.developpeur)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.minimalConfig)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nom)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.tblClassification.nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblGenre.nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblPlatform.nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tblTheme.nom)
                </td>
                <td>
                    @Html.ActionLink("Éditer", "Edit", new { id = item.idJeu }) |
                    @Html.ActionLink("Détails", "Details", new { id = item.idJeu }) |
                    @Html.ActionLink("Supprimer", "Delete", new { id = item.idJeu })
                </td>
            </tr>
        }

    </table>
</div>